# meteoric-sniper config.yaml file

generalConfig: {
  token: 'get',         # main token.
  bot: false,                  # if the main token is a bot or not.
  snipeToken: 'get', # token that gets the nitro from the messages sent. This account will be the one actually finding the nitro to apply to the main token.
  logging: {
    webhook_url: '',                     # webhook to log info to, keep it empty to not do any webhook logging.
    file_name: '/data/meteoric-logs.txt' # file logging, coming soon.
  },

  envConfig: {
    use_env_file: false,       # use .env file, if you're using a public host i highly recommend it.
    token_value_name: 'TOKEN',  # key value of the token inside the .env
    snipe_token_value_name: 'SNIPE_TOKEN'
  }
}
